const mockPosts = [
  {
    id: 1,
    title: "Spam content reported",
    author: { username: "john_doe" },
    reportedReason: "User reported spam links",
    reportedAt: "2025-09-01T10:00:00Z",
    status: "pending",
  },
  {
    id: 2,
    title: "Offensive comment flagged",
    author: { username: "sarah123" },
    reportedReason: "Contains offensive language",
    reportedAt: "2025-09-01T09:30:00Z",
    status: "approved",
  },
  {
    id: 3,
    title: "Fake news detected",
    author: { username: "alex99" },
    reportedReason: "Spreading misinformation",
    reportedAt: "2025-08-31T14:00:00Z",
    status: "rejected",
  },
  {
    id: 4,
    title: "Suspicious account activity",
    author: { username: "bot_account" },
    reportedReason: "Likely a bot",
    reportedAt: "2025-08-30T12:45:00Z",
    status: "pending",
  },
  {
    id: 5,
    title: "Harassment in comments",
    author: { username: "linda" },
    reportedReason: "Reported for targeted harassment",
    reportedAt: "2025-08-29T11:15:00Z",
    status: "pending",
  },

  // ✅ Added 20 more mock posts
  {
    id: 6,
    title: "Copyright violation reported",
    author: { username: "mark42" },
    reportedReason: "Shared pirated material",
    reportedAt: "2025-08-28T15:10:00Z",
    status: "pending",
  },
  {
    id: 7,
    title: "Fake giveaway post",
    author: { username: "giveaway_scam" },
    reportedReason: "Scam attempt",
    reportedAt: "2025-08-27T09:00:00Z",
    status: "rejected",
  },
  {
    id: 8,
    title: "Inappropriate image uploaded",
    author: { username: "emma" },
    reportedReason: "Contains nudity",
    reportedAt: "2025-08-26T19:45:00Z",
    status: "approved",
  },
  {
    id: 9,
    title: "Spam bot detected",
    author: { username: "spam_bot99" },
    reportedReason: "Automated spam detected",
    reportedAt: "2025-08-25T08:20:00Z",
    status: "pending",
  },
  {
    id: 10,
    title: "Fake job listing",
    author: { username: "career_fake" },
    reportedReason: "Scam job advertisement",
    reportedAt: "2025-08-24T13:30:00Z",
    status: "pending",
  },
  {
    id: 11,
    title: "Bullying in chat",
    author: { username: "angry_user" },
    reportedReason: "Reported for bullying",
    reportedAt: "2025-08-23T10:15:00Z",
    status: "approved",
  },
  {
    id: 12,
    title: "Misleading advertisement",
    author: { username: "ad_scammer" },
    reportedReason: "Fake claims",
    reportedAt: "2025-08-22T18:50:00Z",
    status: "rejected",
  },
  {
    id: 13,
    title: "Hate speech post",
    author: { username: "hater123" },
    reportedReason: "Violates community guidelines",
    reportedAt: "2025-08-21T17:25:00Z",
    status: "pending",
  },
  {
    id: 14,
    title: "Off-topic content flood",
    author: { username: "random_guy" },
    reportedReason: "Spammed irrelevant content",
    reportedAt: "2025-08-20T14:10:00Z",
    status: "pending",
  },
  {
    id: 15,
    title: "Duplicate account",
    author: { username: "fake_profile" },
    reportedReason: "User created multiple accounts",
    reportedAt: "2025-08-19T09:40:00Z",
    status: "approved",
  },
  {
    id: 16,
    title: "Political misinformation",
    author: { username: "troll_account" },
    reportedReason: "False claims spreading",
    reportedAt: "2025-08-18T16:00:00Z",
    status: "rejected",
  },
  {
    id: 17,
    title: "Fraudulent charity post",
    author: { username: "charity_fake" },
    reportedReason: "Fake donation request",
    reportedAt: "2025-08-17T11:20:00Z",
    status: "pending",
  },
  {
    id: 18,
    title: "Toxic behavior in forum",
    author: { username: "flamewarrior" },
    reportedReason: "Aggressive language",
    reportedAt: "2025-08-16T20:10:00Z",
    status: "pending",
  },
  {
    id: 19,
    title: "Harmful medical advice",
    author: { username: "fake_doc" },
    reportedReason: "Promoting dangerous remedies",
    reportedAt: "2025-08-15T12:00:00Z",
    status: "approved",
  },
  {
    id: 20,
    title: "Phishing attempt detected",
    author: { username: "phisher" },
    reportedReason: "Fake login page link",
    reportedAt: "2025-08-14T07:30:00Z",
    status: "pending",
  },
  {
    id: 21,
    title: "Violent threats in post",
    author: { username: "threat_guy" },
    reportedReason: "Reported for violent threats",
    reportedAt: "2025-08-13T22:00:00Z",
    status: "pending",
  },
  {
    id: 22,
    title: "Clickbait headline",
    author: { username: "clickbaiter" },
    reportedReason: "Exaggerated misleading title",
    reportedAt: "2025-08-12T15:40:00Z",
    status: "approved",
  },
  {
    id: 23,
    title: "Illegal content shared",
    author: { username: "illegal_poster" },
    reportedReason: "Reported illegal file sharing",
    reportedAt: "2025-08-11T19:25:00Z",
    status: "rejected",
  },
  {
    id: 24,
    title: "Hacked account spam",
    author: { username: "compromised_user" },
    reportedReason: "Hacked account posting spam",
    reportedAt: "2025-08-10T08:10:00Z",
    status: "pending",
  },
  {
    id: 25,
    title: "Offensive meme shared",
    author: { username: "meme_lord" },
    reportedReason: "Contains offensive imagery",
    reportedAt: "2025-08-09T13:55:00Z",
    status: "pending",
  }
];

export default mockPosts;
